title: "@gheniaf's Notes"
description: Website for my personal, technical notes.
theme: just-the-docs

url: /

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark
